name: Build Release Binaries

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
         sudo apt-get update
         sudo apt-get install -y libgl1-mesa-dev libxcursor-dev pkg-config
         sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
         sudo apt-get install -y libxcb-icccm4-dev libx11-xcb-dev libxcb-dri2-0-dev

      - name: Build release binary
        run: cargo xtask bundle bitfiddler --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ runner.os }}
          path: target/bundled/*

  release:
    needs: build  # Ensure all builds finish first
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Archive each directory as .zip
        run: |
          cd artifacts
          for dir in *; do
            if [ -d "$dir" ]; then
              zip -r "$dir.zip" "$dir"
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
          token: ${{ secrets.GITHUB_TOKEN }}
